// components/Navbar.vue
<template>
  <nav class="flex justify-between items-center p-4 bg-gradient-to-r from-blue-700 via-blue-400 to-cyan-400 shadow-lg">
    <!-- Logo -->
    <div class="flex items-center">
      <img src="/lanri.png" alt="Logo" class="h-12 mr-3 p-2 sm:h-16 drop-shadow-lg" />
      <span class="text-white font-extrabold text-xl sm:text-2xl tracking-wide drop-shadow">INOLAND</span>
    </div>

    <!-- Desktop Menu -->
    <div class="hidden md:flex items-center gap-6">
      <ul class="flex gap-6 list-none font-poppins font-bold text-lg text-white">
        <li v-for="item in menu" :key="item.name" class="my-2 md:my-0">
          <NuxtLink
            :to="item.path"
            class="no-underline px-4 py-2 rounded transition font-semibold
              hover:bg-white/80 hover:text-blue-700 hover:shadow-md
              focus:outline-none focus:ring-2 focus:ring-cyan-400"
            :class="{ 'bg-white/90 text-blue-700 shadow font-bold': $route.path === item.path }"
          >
            {{ item.name }}
          </NuxtLink>
        </li>
      </ul>
    </div>

    <!-- Right Side (Profile, Language, Hamburger) -->
    <div class="flex items-center gap-4">
      <!-- Hamburger Menu for Mobile -->
      <button class="md:hidden text-white" @click="toggleMenu">
        <svg class="w-7 h-7" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
        </svg>
      </button>

      <!-- Mobile Menu -->
      <ul
        class="absolute top-full left-0 w-full bg-gradient-to-r from-blue-700 via-blue-400 to-cyan-400 shadow-lg rounded-b-lg p-4 md:hidden list-none font-poppins font-bold text-lg text-white z-30"
        :class="{ 'block': isMenuOpen, 'hidden': !isMenuOpen }"
      >
        <li v-for="item in menu" :key="item.name" class="my-2 md:my-0">
          <NuxtLink
            :to="item.path"
            class="no-underline px-4 py-2 rounded block transition font-semibold
              hover:bg-white/80 hover:text-blue-700 hover:shadow-md"
            @click="toggleMenu"
          >
            {{ item.name }}
          </NuxtLink>
        </li>
      </ul>

      <!-- Profile Dropdown -->
      <div v-if="userProfile" class="relative">
        <button
          class="text-white text-lg cursor-pointer border-none bg-transparent hover:text-cyan-100 transition"
          @click="toggleProfile"
        >
          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20">
            <path fill-rule="evenodd" d="M10 9a3 3 0 100-6 3 3 0 000 6zm-7 9a7 7 0 1114 0H3z" clip-rule="evenodd"></path>
          </svg>
        </button>

        <div v-if="isProfileOpen" class="absolute right-0 mt-2 w-52 bg-white rounded-md shadow-xl py-2 z-40 border border-blue-200">
          <p class="px-4 py-2 text-sm text-blue-700 font-semibold">
            Selamat Datang, {{ userProfile.nama_lengkap }} dari {{ userProfile.instansi }}!
          </p>
          <NuxtLink to="/admin" class="block px-4 py-2 text-sm text-blue-700 hover:bg-blue-50">
            Admin
          </NuxtLink>
          <NuxtLink to="/dashboard" class="block px-4 py-2 text-sm text-blue-700 hover:bg-blue-50">
            Dashboard
          </NuxtLink>
          <button
            @click="handleLogout"
            class="block w-full text-left px-4 py-2 text-sm text-blue-700 hover:bg-blue-50"
          >
            Logout
          </button>
        </div>
      </div>

      <!-- Tombol Masuk -->
      <button
        v-else
        @click="openModal"
        class="border-2 border-white bg-gradient-to-r from-cyan-400 to-blue-700 text-white py-2 px-4 rounded-lg cursor-pointer text-lg font-bold shadow hover:bg-white hover:text-blue-700 transition"
      >
        Masuk
      </button>

      <!-- Language Selector -->
      <div class="flex gap-2">
        <button @click="changeLanguage('en')" class="bg-transparent border-none cursor-pointer">
          <img src="/uk_flag.png" alt="English" class="border border-gray-300 rounded-md shadow" width="30" height="20" />
        </button>
        <button @click="changeLanguage('id')" class="bg-transparent border-none cursor-pointer">
          <img src="/indonesia_flag.png" alt="Bahasa Indonesia" class="border border-gray-300 rounded-md shadow" width="30" height="20" />
        </button>
      </div>
    </div>

    <!-- Login Modal -->
    <Login v-if="isModalOpen" :show="isModalOpen" @close="closeModal" />
  </nav>
</template>

<script setup>
import { ref } from 'vue'
import Login from '~/components/Login.vue'

// State
const isModalOpen = ref(false)
const isMenuOpen = ref(false)
const isProfileOpen = ref(false)
const userProfile = ref(null)

// Menu navbar
const menu = [
  { name: 'Beranda', path: '/' },
  { name: 'Layanan Inovasi', path: '/layanan' },
  { name: 'Cari Inovasi', path: '/cari' },
  { name: 'Referensi', path: '/referensi' },
  { name: 'Gallery', path: '/gallery' }
]

// Fungsi
function openModal() {
  isModalOpen.value = true
}

function closeModal() {
  isModalOpen.value = false
}

function toggleMenu() {
  isMenuOpen.value = !isMenuOpen.value
}

function toggleProfile() {
  isProfileOpen.value = !isProfileOpen.value
}

function changeLanguage(lng) {
  // Implementasi change language nanti jika diperlukan
}

async function handleLogout() {
  try {
    const res = await $fetch('/api/auth/logout', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      }
    })
    if (res.success) {
      userProfile.value = null
    }
  } catch (error) {
    // Optional: handle error
  }
}
</script>

// src/app/components/Navbar.tsx
'use client';

import { useState, useEffect } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useTranslation } from 'react-i18next';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faUser } from '@fortawesome/free-solid-svg-icons';
import Login from './Login';

interface UserProfile {
  nama_lengkap: string;
}

const Navbar = () => {
  const [isModalOpen, setModalOpen] = useState(false);
  const [userProfile, setUserProfile] = useState<UserProfile | null>(null);
  const [isMenuOpen, setMenuOpen] = useState(false);
  const [isProfileOpen, setProfileOpen] = useState(false);
  const { t, i18n } = useTranslation();
  const router = useRouter();

  useEffect(() => {
    const storedUser = localStorage.getItem('userProfile');
    if (storedUser) {
      setUserProfile(JSON.parse(storedUser));
    }
  }, []);

  const handleLogout = () => {
    localStorage.removeItem('userProfile');
    setUserProfile(null);
    router.push('/');
  };

  const menu = [
    { name: t('Beranda'), path: '/' },
    { name: t('Layanan Inovasi'), path: '/layanan' },
    { name: t('Cari Inovasi'), path: '/cari' },
    { name: t('Referensi'), path: '/referensi' },
    { name: t('Pengetahuan'), path: '/pengetahuan' },
  ];

  const changeLanguage = (lng: string) => {
    i18n.changeLanguage(lng);
  };

  return (
    <>
      {/* Navbar */}
      <nav className="flex justify-between items-center p-4 bg-[#3781c8] shadow-md z-50 border-b border-gray-300 relative">
        <div className="flex items-center">
          <Image src="/lanri.png" alt="Logo" width={100} height={100} className="mr-3 p-2" />
          <span className="text-white font-bold text-xl sm:text-4xl">INOLAND</span>
        </div>

        {/* Desktop Menu */}
        <div className="hidden md:flex items-center gap-6">
          <ul className="flex gap-6 font-poppins font-bold text-lg text-white">
            {menu.map((item) => (
              <li key={item.name}>
                <Link href={item.path} className="hover:text-[#3781c8] hover:bg-white p-2 rounded">
                  {item.name}
                </Link>
              </li>
            ))}
          </ul>
        </div>

        {/* Right Section (Profile & Language) */}
        <div className="flex items-center gap-4">
          {/* Mobile Menu Toggle */}
          <button className="md:hidden text-white" onClick={() => { 
            setMenuOpen(!isMenuOpen); 
            console.log("Menu state:", !isMenuOpen); 
          }}>
            ☰
          </button>

          {/* Mobile Menu Dropdown */}
          {isMenuOpen && (
            <ul className="absolute top-full left-0 w-full bg-white shadow-lg rounded-lg p-4 md:hidden z-50">
              {menu.map((item) => (
                <li key={item.name}>
                  <Link href={item.path} className="text-[#3781c8] hover:bg-[#3781c8] hover:text-white block p-2 rounded">
                    {item.name}
                  </Link>
                </li>
              ))}
            </ul>
          )}

          {/* User Profile */}
          {userProfile ? (
            <div className="relative">
              <button onClick={() => setProfileOpen(!isProfileOpen)}>
                <FontAwesomeIcon icon={faUser} className="text-white text-lg" />
              </button>
              {isProfileOpen && (
                <div className="absolute right-0 mt-2 w-48 bg-white rounded-md shadow-lg py-2 z-20">
                  <p className="px-4 py-2 text-sm text-gray-700">{t('Selamat Datang')}, {userProfile.nama_lengkap}!</p>
                  <Link href="/dashboard" className="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">{t('Dashboard')}</Link>
                  <button onClick={handleLogout} className="block w-full text-left px-4 py-2 text-sm text-gray-700 hover:bg-gray-100">
                    {t('Logout')}
                  </button>
                </div>
              )}
            </div>
          ) : (
            <button onClick={() => setModalOpen(true)} className="border-2 border-white bg-[#3781c8] text-white py-2 px-4 rounded-lg">
              {t('Masuk')}
            </button>
          )}

          {/* Language Selector */}
          <div className="flex gap-2">
            <button onClick={() => changeLanguage('en')}>
              <Image src="/uk_flag.png" alt="English" width={30} height={20} className="border border-gray-300 rounded-md" />
            </button>
            <button onClick={() => changeLanguage('id')}>
              <Image src="/indonesia_flag.png" alt="Bahasa Indonesia" width={30} height={20} className="border border-gray-300 rounded-md" />
            </button>
          </div>
        </div>
      </nav>

      {/* Modal Login */}
      {isModalOpen && (
        <div className="fixed inset-0 flex items-center justify-center bg-black bg-opacity-30 z-40">
          <div className="bg-white p-8 rounded shadow-lg w-1/3 relative">
            <button 
              className="absolute top-2 right-2 text-gray-500 hover:text-gray-800" 
              onClick={() => setModalOpen(false)}
            >
              ✖
            </button>
            <Login 
              isOpen={isModalOpen} 
              onClose={() => setModalOpen(false)} 
              onLoginSuccess={(loggedInUser: UserProfile) => {
                localStorage.setItem('userProfile', JSON.stringify(loggedInUser));
                setUserProfile(loggedInUser);
                setModalOpen(false);
              }} 
            />
          </div>
        </div>
      )}
    </>
  );
};

export default Navbar;
